### ISSUE TITLE
Add preferences to prototype windows.

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#10]
Under Prototype (Browser Window), add a window with an about:preferences page.

**Comment by aaronrbenson** [comment]
Many of these now exist in the in-content library (pending some style updates).

![screen shot 2018-02-28 at 4 43 46 pm](https://user-images.githubusercontent.com/139451/36817448-d0a8e166-1ca6-11e8-9e99-081555c2609c.png)
