### ISSUE TITLE
Add radio button to Input Controls

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#11]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/473531/35582957-5f831e74-05be-11e8-8143-910289ad7e9f.png">

Need a radio button in the input controls folder.

![image](https://user-images.githubusercontent.com/473531/35582979-6ded8e22-05be-11e8-90bf-64977cb296f0.png)

**Comment by aaronrbenson** [comment]
These now exist in the in-content library ...

![screen shot 2018-02-28 at 4 42 19 pm](https://user-images.githubusercontent.com/139451/36817320-5ce46afc-1ca6-11e8-8568-51b0198a6d6d.png)
