### ISSUE TITLE
Need a downloads panel

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#12]
Doing some work on the Downloads panel and it doesn't exist in the Library. There is a Downloads view in the Library section on the Menu, but no actual downloads panel.

**Comment by aminalhazwani** [comment]
<img width="318" alt="screen shot 2018-06-14 at 4 53 30 pm" src="https://user-images.githubusercontent.com/1721875/41443736-7cb05972-6ff3-11e8-8745-e6864ab3703b.png">

We now have one 🙌
