### ISSUE TITLE
Application Menu missing Exit etry

### ISSUE THREAD

**Issue by designakt** [FirefoxUX/photon-library#14]
In the Windows 10 Libaries Application Menu, the last entry is missing.
This is what it looks like on Windows:
![application_menu-exit-firefox](https://user-images.githubusercontent.com/8145891/36534587-4ce6e3ca-17c7-11e8-9204-f5633a429ad6.PNG)

Here is an updated Application Menu I use:
[WindowsApplicationMenuUpdate.zip](https://github.com/FirefoxUX/photon-library/files/1747630/WindowsApplicationMenuUpdate.zip)
(I also fixed the Shortcuts to be Windows Shortcuts and added an ellipsis to Customize)

**Comment by aminalhazwani** [comment]
<img width="304" alt="screen shot 2018-06-14 at 1 25 58 pm" src="https://user-images.githubusercontent.com/1721875/41436461-94379f96-6fd6-11e8-8889-fdf7fb707a76.png">

Looks like it's fixed now 🙂
