### ISSUE TITLE
Library should have search examples

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#15]
An example of the awesome bar in action would be a super helpful addition to this library.

**Comment by aminalhazwani** [comment]
<img width="899" alt="screen shot 2018-06-14 at 1 21 33 pm" src="https://user-images.githubusercontent.com/1721875/41436242-e2e1d6b2-6fd5-11e8-8143-f0cd03aa61cd.png">

We have one now! 🙂
