### ISSUE TITLE
Wrong font in Windows 10 Template

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#17]
In the Windows 10 template this text element uses Open Sans while the rest use Segoe.

![image](https://user-images.githubusercontent.com/473531/39939241-981955c8-5523-11e8-9d0c-975ba6856975.png)

**Comment by aminalhazwani** [comment]
<img width="867" alt="screen shot 2018-06-14 at 1 22 40 pm" src="https://user-images.githubusercontent.com/1721875/41436290-0774a0e0-6fd6-11e8-8625-7cb3a0685630.png">

Fixed now!
