### ISSUE TITLE
Make small text grey

### ISSUE THREAD

**Issue by ryanfeeley** [FirefoxUX/photon-library#19]
Now that the small text in the control center is grey, the sketch files need updating..
<img width="329" alt="image" src="https://user-images.githubusercontent.com/68213/41607015-0b91aaca-73b3-11e8-8102-1fad4590b615.png">

**Comment by shorlander** [comment]
This should be fixed now.

**Comment by aminalhazwani** [comment]
<img width="522" alt="screen shot 2018-06-20 at 9 15 56 am" src="https://user-images.githubusercontent.com/1721875/41643114-a580ddd8-746a-11e8-91ee-115b8c6c3ff2.png">

Affirmative!
