### ISSUE TITLE
Overlap between the "In content" and "Windows 10" library

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/photon-library#20]
We noticed that the In Content library and the Windows 10 libraries have some overlaps, like for primary buttons. What if atomic elements live in the base library? Or do you have a better solution maybe?

**Comment by shorlander** [comment]
Talked this over. Many different ways to break this down to reduce number of libraries, redundancy of parts, but still have the right amount of platform coverage.

Our proposal is:
- Base / Foundation Library = Platform agnostic elements; e.g. icons, colors
- Components Library = Contains all of the base Components for *all* platforms; e.g. buttons, doorhangers, checkboxes, etc.
- Browser Chrome Library * 3: Windows, Mac, Linux
- In Content Library * 3: Windows, Mac, Linux

Browser Chrome and In Content Libraries would pull from the Components and Base Libraries.

**Comment by aminalhazwani** [comment]
Thanks for talking this over @shorlander! It looks like a good plan, I only have a couple of questions!

- Would the base library contains colors, icons, ... for the desktop platforms or also mobile and others platforms?
- Would the components library contains only desktop elements or also mobile elements? 
- Related to the questions above, if the base and component library do not contain the mobile/tv/touchbar/... elements and attributes we should figure out a way to keep the content in sync if we add icons, colors, etc.
- When you write “* 3” do you mean three separate libraries or the same component with a three different system font?
- We should document this new approach and set up a way to make sure that such overlap does not happen, any idea?

**Comment by brassy-** [comment]
New plan on this issue by next week.

**Comment by aminalhazwani** [comment]
Sep 13th update: @shorlander has a rough that will share soon 🙂

**Comment by aminalhazwani** [comment]
@shorlander plan less rough but we will wait for Sketch 52 as it makes things easier!
