### ISSUE TITLE
Button size doesn't match DSG guidelines

### ISSUE THREAD

**Issue by AmyYLee** [FirefoxUX/photon-library#21]
<img width="978" alt="screen shot 2018-07-20 at 13 01 50" src="https://user-images.githubusercontent.com/5992746/43015284-3bf9d80e-8c1d-11e8-868c-2eafd14a2f16.png">

The [DSG guideline](https://design.firefox.com/photon/components/buttons.html) states buttons are 32px high and minimum width is 132px. The button component doesn't match (30px x 150px)

Thanks!

**Comment by brassy-** [comment]
Aaron will change it and see what it's going to break.
