### ISSUE TITLE
Provide more examples of screenshots in Highlight card symbols

### ISSUE THREAD

**Issue by AmyYLee** [FirefoxUX/photon-library#28]

**Comment by aaronrbenson** [comment]
Hey @AmyYLee -- not sure what you mean here. Can you elaborate some more?

**Comment by AmyYLee** [comment]
<img width="753" alt="screen shot 2018-09-13 at 10 10 32" src="https://user-images.githubusercontent.com/5992746/45493817-9e359580-b73d-11e8-8e37-c80ea7641087.png">
Like the examples above

**Comment by shorlander** [comment]
Can we expand this a bit? Besides examples it would be nice to break down the components of a card and how they are used / defined. Right now they feel a little free form and under described.

For example: if I wanted to use a card in another context (not New Tab) what would I do?

**Comment by aaronrbenson** [comment]
@shorlander yeah good idea. We discussed in triage this morning that we should include some more definition around card usage in the DSG website. We can track that separately but I'm not sure if it makes sense as an issue in this repo. Thoughts @aminalhazwani ?

**Comment by aminalhazwani** [comment]
@aaronrbenson I opened https://github.com/FirefoxUX/photon/issues/320 🙂 cc @brassy-

**Comment by aminalhazwani** [comment]
We clarified Amy request -- we just need to add more variety to the thumbnails.
