### ISSUE TITLE
Alignment in sidebar component header is a little off

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#3]
The alignment in this row is off:

![screen shot 2018-01-10 at 3 57 16 pm](https://user-images.githubusercontent.com/473531/34795116-f64e9090-f61e-11e7-9344-ccd53af05d9f.png)

**Comment by aminalhazwani** [comment]
<img width="214" alt="screen shot 2018-06-14 at 5 00 56 pm" src="https://user-images.githubusercontent.com/1721875/41443911-85f903f2-6ff4-11e8-8592-5c49c3305ee0.png">

Looks good now 🎉
