### ISSUE TITLE
Provide Dark Theme versions of "detailed" icons

### ISSUE THREAD

**Issue by AmyYLee** [FirefoxUX/photon-library#30]
Hi, 

It would be great to have dark theme versions of the icons found in the sidebar and toolbar in the Library. Thanks!

<img width="140" alt="screen shot 2018-09-24 at 13 36 18" src="https://user-images.githubusercontent.com/5992746/45968474-171ad400-bfff-11e8-8707-bfad0b30a09a.png">

**Comment by aminalhazwani** [comment]
We will wait for Sketch 52 (and their library styles) as it makes things much easier for customization.
