### ISSUE TITLE
Upload Sketch files to this repository

### ISSUE THREAD

**Issue by dannycolin** [FirefoxUX/photon-library#36]
Hi,

I've asked (#ux on IRC) if there was more recent mockups than the one on the Wiki and bwinton suggested me to open an issue here. 

So my question is : Would it be possible to have access to the SVG and/or Sketch files you use for Firefox? 

Thanks,

**Comment by dannycolin** [comment]
Eh @aminalhazwani sorry to bother you but I was wondering if that repo is still active or if I should open a request for the sketch files somewhere else?

**Comment by aminalhazwani** [comment]
Hey @dannycolin I stopped working for Mozilla last year but you can give a try here https://github.com/FirefoxUX/photon-library. As far as I remember we wanted to leverage Sketch Cloud to distribute Sketch libraries but when I left it still was an ongoing discussion.
