### ISSUE TITLE
Sidebar element and sidebar in browser are different widths

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#5]
The sidebar element in the library is a smaller width than the sidebar that comes grouped in the browser. They should probably be the same for consistency.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/473531/34848214-fc6e0e38-f6eb-11e7-8e58-cc7ba8f41293.png">

**Comment by aminalhazwani** [comment]
@sevaan you can change the width of the Sketch symbol 😉
