### ISSUE TITLE
Firefox logos in library are out of date

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#6]
The old logo is being used throughout the library (e.g. in the favicons):

<img width="137" alt="image" src="https://user-images.githubusercontent.com/473531/34880330-2413a672-f77e-11e7-8a37-00936d7773a8.png">

**Comment by sevaan** [comment]
No, that's not true...not throughout the library...

Here's where I found these old ones:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/473531/34880573-dd34b15a-f77e-11e7-8331-5cf868426c13.png">

**Comment by aminalhazwani** [comment]
<img width="218" alt="screen shot 2018-06-14 at 4 57 58 pm" src="https://user-images.githubusercontent.com/1721875/41443829-1b8b0858-6ff4-11e8-943f-9301c443910f.png">

Almost there...

**Comment by shorlander** [comment]
Fixed.
