### ISSUE TITLE
Create application menu w/ slideover panel

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/photon-library#9]
Some menu options cause a panel to slideover in the application menu. We should have an example of that to build off of. Thanks!

**Comment by aminalhazwani** [comment]
<img width="346" alt="screen shot 2018-06-14 at 4 55 14 pm" src="https://user-images.githubusercontent.com/1721875/41443782-ba8ccf82-6ff3-11e8-82fc-67ddd5a54868.png">

And also the slideover panel is now in the library!
